#!/bin/bash
export TEST="LICENSE"
export FILES="/tmp/a;/tmp/b;/tmp/c"
export LICENSE="6200@pbs"
export USERNAME="pbsadmin"
export SOFTWARE="abaqus"
/bin/bash /var/spool/web-pbs/software/abaqus/presubmit  1>>/var/spool/web-pbs/scripts/qsub_5b4af147c937c 2>/var/spool/web-pbs/scripts/pre_5b4af147c9aba.log